prompts: List 3 benefits of meditation

providers:
  - openai:gpt-4

tests:
  - vars:
      input: List 3 benefits of meditation
    assert:
      - type: model-graded-closedqa
        value: Does the output provide a clear and complete answer to the prompt?
      - type: model-graded-closedqa
        value: Does the response stay relevant to the user's prompt?
      - type: model-graded-closedqa
        value: Is the output coherent, logically structured, and easy to follow?